name: Annapolis
favicon: null
layout_spectrum: 0.7761634225025773
typography_spectrum: 0.666664257645607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.030529591254889965
  lightness: 0.8335983690340072
  saturation: 0.15556398732587695
  rhythmicContrast: 0.8416080644819885
purpose: []
